### PR TITLE
Add getCurrentItem method in MenuHelper

### PR DESCRIPTION
**Pull request by fsevestre**
This integrates https://github.com/KnpLabs/KnpMenu/pull/228. (done)

This PR must be merge after the one on KnpMenu library.

### CODE REVIEW

**Comment by dbojdo** [comment]
Hi guys! Mayby it's time to merge this pull request in order to support get_current_item, especially https://github.com/KnpLabs/KnpMenu/pull/228 has been merged. Thanks.

**Comment by dbu** [comment]
https://github.com/KnpLabs/KnpMenu/pull/228 needed a release. i just tagged 2.2 that includes this. please update this PR to bump the version of knp menu to ^2.2.0 . if this is installed with knp menu 2.1.* you would get a fatal error if that method is called. also please bump the branch alias in composer.json

**Comment by fsevestre** [comment]
Just changed the version of KnpMenu and the branch alias in the `composer.json` file.

I don't know if it will have an impact but the tag name is `2.2.0` and don't start with a `v` like the others.

**Comment by dbu** [comment]
v2.0.0 versus 2.0.0 is normalized by composer, it understands both.

**Comment by nckenn** [comment]
Can you make a release version of this??

**Comment by dbu** [comment]
there you go: https://github.com/KnpLabs/KnpMenuBundle/releases/tag/2.1.3

**Comment by stof** [comment]
@dbu asking to change the branch alias to 2.2 due to adding a new feature and then releasing it as 2.1.3 is weird 😄

**Comment by dbu** [comment]
oops. at least it was not a BC break. but sorry, should have been 2.2.0.

**Pull request merged**
