### PR TITLE
Add PHP 7 on Travis

### PR DESCRIPTION
**Pull request by Soullivaneuh**

### CODE REVIEW

**Comment by TomasVotruba** [comment]
:+1:

**Comment by Nek-** [comment]
Why allowing failure as our [builds pass on PHP7 for a while](https://twitter.com/Nekdev/status/618521081121517568) ? :-)

**Comment by Soullivaneuh** [comment]
Didn't know if PHP7 passes or not. Will update it.

**Comment by Soullivaneuh** [comment]
@Nek- done.

**Comment by stof** [comment]
thanks

**Comment by TomasVotruba** [comment]
@stof Thanks

**Pull request merged**
