### PR TITLE
Don't use the deprecated interface with Symfony 4.2

### PR DESCRIPTION
**Pull request by hacfi**
As there is no update to #396 I'm creating a new PR instead.

### CODE REVIEW

**Comment by QuentinCurtet** [comment]
Any update on this ?

**Comment by althaus** [comment]
So... can someone merge this or #396 ?

**Comment by garak** [comment]
Really, can we have a merge and a new release? Last one was in 2017...

**Comment by emodric** [comment]
Now all we need is a release :)

**Pull request merged**
