### PR TITLE
chore: add ci tests for php 8.3

### PR DESCRIPTION
**Pull request by Chris53897**

### CODE REVIEW

**Review by derrabus — APPROVED** [review]

**Review by garak — CHANGES_REQUESTED** [review]
"Dev deps" should test against php 8.3 as well

**Comment by Chris53897** [comment]
@garak You want this to be changed to 8.3 (see new commit) or additional "Dev deps" tests to 8.2?

**Review by garak — APPROVED** [review]

**Review by garak — CHANGES_REQUESTED** [review]
Hello @Chris53897 
it seems you need to find a PHPUnit configuration compatible with both 9.6 and 10.0 PHPUnit versions.

**Comment by Chris53897** [comment]
I am not sure if this is possible.

Possible solutions
a) two seperate xml-files
b) stick with phpunit 9
c) Just ignore/silence the deprecation warning (preferred by me)
...

I suggest that the error should be fixed upfront. I am not sure if it is already fixed.

**Comment by Chris53897** [comment]
Sorry for late response. I forgot about this PR

**Review by derrabus — APPROVED** [review]

**Review by garak — APPROVED** [review]

**Pull request merged**
