### PR TITLE
fix doc link

### PR DESCRIPTION
**Pull request by mhor**

### CODE REVIEW

**Comment by Nek-** [comment]
:+1: nice catch ^^

**Comment by stof** [comment]
Cna you switch it to a relative link (using ``Resources/doc/index.rst``) so that github makes it point to the same version than the one the readme is displayed for ? It will be even better.

@javiereguiluz is there any ETA for having it rendered on symfony.com ?

**Comment by mhor** [comment]
@stof done :+1:

**Comment by stof** [comment]
thanks

**Comment by javiereguiluz** [comment]
@stof I don't know when will the bundles' doc be integrated in symfony.com, but I guess it will be integrated soon because everything is working OK locally:

knpmenubundle_in_symfony_com

**Comment by stof** [comment]
@javiereguiluz it would be great to have it soon, because configuration blocks don't render on github, so this means we need to have a rendered doc somewhere else. If it does not come on symfony.com soon enough, this would require doing a RTD setup to avoid breaking the DX. Who would know about this ETA ?

Btw, I see a bug in your screenshot: the URL says ``master`` but the version switcher says ``1.1``. the master branch of KnpMenuBundle is not 1.1. It is 2.0 (and the 1.1 doc has not been converted to rST)

**Pull request merged**
